version: '3.7'

services:
  couchbase:
    image: couchbase/server:latest
    container_name: couchbase_server
    environment:
      - COUCHBASE_SERVER_NAME=couchbase
      - COUCHBASE_BUCKET=delivery
      - COUCHBASE_USER=admin
      - COUCHBASE_PASSWORD=test123
    ports:
      - "8091:8091" # Web Console
      - "8093:8093" # Couchbase REST API
      - "11210:11210" # Couchbase Data/Query
    volumes:
      - couchbase_data:/opt/couchbase/var

volumes:
  couchbase_data:
